apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: ae8mp7faz-go 
  janus-idp.io/tekton: ae8mp7faz-go
  backstage.io/kubernetes-id: ae8mp7faz-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ae8mp7faz-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  