apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: ae8mp7faz-go
  janus-idp.io/tekton: ae8mp7faz-go
  backstage.io/kubernetes-id: ae8mp7faz-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ae8mp7faz-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
