apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: ae8mp7faz-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ae8mp7faz-go 
  name: ae8mp7faz-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: ae8mp7faz-go 
