apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: ae8mp7faz-go
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-55262613e3.su0l.p3.openshiftapps.com/rhtap/rhtap-qe:b21fe7c5a073e490a6b48838e4b9ecb457ccadf0@sha256:35481e39a2be55a7bbc954f661810277402b7e08174222278e4614fcbb3727b3
          name: container-image
